export interface Sermon {
  id: string;
  title: string;
  speaker: string;
  date: string;
  duration: string;
  seriesId?: string;
  category: string;
  description: string;
  scriptures: string[];
  tags: string[];
  notes?: string;
  hasAudio: boolean;
  hasVideo: boolean;
  hasNotes: boolean;
  isFeatured?: boolean;
}

export interface SermonSeries {
  id: string;
  name: string;
  description: string;
  sermonCount: number;
  coverGradient: string;
  startDate: string;
  endDate?: string;
}

export const sermonCategories = [
  "All",
  "Sunday Service",
  "Bible Study",
  "Special Programme",
  "Faith Clinic",
  "Midweek Service",
];

export const sortOptions = [
  { value: "newest", label: "Newest First" },
  { value: "oldest", label: "Oldest First" },
  { value: "title-az", label: "Title A-Z" },
  { value: "title-za", label: "Title Z-A" },
];

export const mockSermonSeries: SermonSeries[] = [
  {
    id: "ss1",
    name: "Walking in Destiny",
    description: "Discovering and fulfilling your God-given purpose through faith, obedience, and the Holy Spirit's guidance.",
    sermonCount: 6,
    coverGradient: "from-[#1A237E] to-[#3949AB]",
    startDate: "2025-06-08",
    endDate: "2025-07-13",
  },
  {
    id: "ss2",
    name: "Prayer That Moves Mountains",
    description: "Learning the secrets of effectual, fervent prayer that brings down divine intervention and breakthroughs.",
    sermonCount: 5,
    coverGradient: "from-[#D32F2F] to-[#B71C1C]",
    startDate: "2025-06-13",
    endDate: "2025-07-04",
  },
  {
    id: "ss3",
    name: "The Grace Life",
    description: "Understanding God's unmerited favour and learning to walk in grace every single day.",
    sermonCount: 5,
    coverGradient: "from-[#2E7D32] to-[#1B5E20]",
    startDate: "2025-04-27",
    endDate: "2025-05-25",
  },
  {
    id: "ss4",
    name: "Spiritual Warfare",
    description: "Equipping believers with spiritual armour and strategies for victorious warfare against the forces of darkness.",
    sermonCount: 4,
    coverGradient: "from-[#4A148C] to-[#311B92]",
    startDate: "2025-04-03",
    endDate: "2025-04-24",
  },
  {
    id: "ss5",
    name: "Family Matters",
    description: "Building godly homes, nurturing children in the Lord, and establishing strong family foundations rooted in the Word.",
    sermonCount: 4,
    coverGradient: "from-[#E65100] to-[#BF360C]",
    startDate: "2025-04-24",
    endDate: "2025-05-15",
  },
];

export const mockSermons: Sermon[] = [
  // Series 1: Walking in Destiny
  {
    id: "ser1",
    title: "Discovering Your Purpose",
    speaker: "Pastor [Name]",
    date: "2025-07-13",
    duration: "48:32",
    seriesId: "ss1",
    category: "Sunday Service",
    description: "Every person was created with a divine purpose. In this opening message of the Walking in Destiny series, we explore how to discover your God-ordained destiny through the Word of God, prayer, and the leading of the Holy Spirit. You are not an accident; you were designed for greatness.",
    scriptures: ["Jeremiah 29:11", "Ephesians 2:10", "Proverbs 19:21"],
    tags: ["purpose", "destiny", "calling"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    isFeatured: true,
    notes: "Key Points:\n\n1. God has a specific plan for your life (Jer. 29:11)\n2. Your purpose is discovered through intimacy with God\n3. The Holy Spirit is your guide into all truth\n4. Purpose is not about you but about those you are called to serve\n5. When you walk in purpose, God provides the grace\n\nMemory Verse: 'For we are His workmanship, created in Christ Jesus for good works, which God prepared beforehand that we should walk in them.' - Ephesians 2:10",
  },
  {
    id: "ser2",
    title: "Steps to Destiny Fulfillment",
    speaker: "Pastor [Name]",
    date: "2025-07-06",
    duration: "52:15",
    seriesId: "ss1",
    category: "Sunday Service",
    description: "Discovery of purpose is only the beginning. In this message, we outline practical, biblical steps every believer must take to move from merely knowing their purpose to actually fulfilling it. Faith without works is dead — your destiny requires active participation.",
    scriptures: ["James 2:17-26", "Philippians 3:12-14", "Hebrews 12:1-2"],
    tags: ["action", "faith", "obedience"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Faith must be accompanied by corresponding action\n2. Press toward the mark of the high calling (Phil. 3:14)\n3. Lay aside every weight and sin that easily ensnares\n4. Destiny is fulfilled step by step, not overnight\n5. Keep your eyes on Jesus, the author and finisher of faith",
  },
  {
    id: "ser3",
    title: "Overcoming Destiny Delay",
    speaker: "Pastor [Name]",
    date: "2025-06-29",
    duration: "45:18",
    seriesId: "ss1",
    category: "Sunday Service",
    description: "When God's timing seems different from yours, how do you respond? This sermon addresses the pain and frustration of delayed destiny, drawing from the lives of Abraham, Joseph, and David — men who all faced significant delays before seeing God's promises fulfilled.",
    scriptures: ["Habakkuk 2:3", "Hebrews 10:35-36", "Isaiah 40:31"],
    tags: ["patience", "timing", "perseverance"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Delay is not denial — God's timing is perfect\n2. While you wait, prepare (David serving Saul before the throne)\n3. Abraham waited 25 years — but the promise came\n4. Joseph's delay was actually his preparation\n5. Those who wait upon the Lord shall renew their strength",
  },
  {
    id: "ser4",
    title: "The Power of Vision",
    speaker: "Pastor [Name]",
    date: "2025-06-22",
    duration: "50:10",
    seriesId: "ss1",
    category: "Sunday Service",
    description: "A clear vision from God sustains you through every season of life. Without vision, the people perish. This message teaches how to receive, nurture, and run with the vision God has given you for your life, family, and ministry.",
    scriptures: ["Proverbs 29:18", "Habakkuk 2:2-3", "Genesis 15:1"],
    tags: ["vision", "focus", "direction"],
    hasAudio: true,
    hasVideo: false,
    hasNotes: true,
    notes: "Key Points:\n\n1. Write the vision and make it plain (Hab. 2:2)\n2. Vision is the compass for your destiny\n3. Protect your vision from doubt and distraction\n4. A God-given vision will always align with His Word\n5. Run with the vision — it has an appointed time",
  },
  {
    id: "ser5",
    title: "Destiny Helpers",
    speaker: "Pastor [Name]",
    date: "2025-06-15",
    duration: "47:55",
    seriesId: "ss1",
    category: "Midweek Service",
    description: "God has assigned specific people to help you fulfill your destiny — but you must recognize and position yourself to receive them. From the story of Naomi and Ruth to Elijah and Elisha, this sermon reveals how God uses destiny helpers to accelerate your journey.",
    scriptures: ["Ruth 2:1-23", "1 Kings 19:19-21", "Luke 5:1-11"],
    tags: ["relationships", "mentors", "divine connections"],
    hasAudio: true,
    hasVideo: false,
    hasNotes: false,
  },
  {
    id: "ser6",
    title: "Finishing Strong",
    speaker: "Pastor [Name]",
    date: "2025-06-08",
    duration: "51:30",
    seriesId: "ss1",
    category: "Sunday Service",
    description: "The race is not to the swift but to those who endure to the end. The concluding message of the Walking in Destiny series focuses on how to finish your course with joy, avoiding the pitfalls that have caused many to abandon their God-given assignments mid-way.",
    scriptures: ["2 Timothy 4:7-8", "Ecclesiastes 7:8", "1 Corinthians 9:24-27"],
    tags: ["endurance", "perseverance", "victory"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Paul finished his race — so can you (2 Tim. 4:7)\n2. Better is the end of a thing than its beginning (Eccl. 7:8)\n3. Discipline your body to keep it under control\n4. Keep your eyes on the eternal prize\n5. Surround yourself with people who will hold you accountable",
  },

  // Series 2: Prayer That Moves Mountains
  {
    id: "ser7",
    title: "The Secret Place of Prayer",
    speaker: "Pastor [Name]",
    date: "2025-07-02",
    duration: "55:40",
    seriesId: "ss2",
    category: "Tuesday Bible Study",
    description: "The most powerful prayers are birthed in the secret place — that quiet, intimate communion with God where nobody else sees. Jesus modelled this lifestyle, rising early to pray in solitary places. This sermon teaches how to cultivate and maximise your personal prayer closet.",
    scriptures: ["Matthew 6:6", "Mark 1:35", "Psalm 91:1"],
    tags: ["prayer", "intimacy", "secret place"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. The secret place is where real power is generated\n2. God rewards those who pray in secret (Matt. 6:6)\n3. Jesus Himself modelled early morning prayer\n4. He who dwells in the secret place abides under the shadow of the Almighty\n5. Consistency in the secret place produces visible results",
  },
  {
    id: "ser8",
    title: "Praying with Authority",
    speaker: "Pastor [Name]",
    date: "2025-06-25",
    duration: "42:22",
    seriesId: "ss2",
    category: "Faith Clinic",
    description: "You have been given authority in the name of Jesus and through the Word of God. This sermon empowers believers to pray with boldness and authority, shifting from passive, wishful prayers to commanding, faith-filled declarations that enforce the will of God on earth.",
    scriptures: ["Luke 10:19", "Mark 11:23-24", "James 5:16"],
    tags: ["authority", "declaration", "faith"],
    hasAudio: true,
    hasVideo: false,
    hasNotes: true,
    notes: "Key Points:\n\n1. You have been given authority over all the power of the enemy (Luke 10:19)\n2. Speak to the mountain, not about the mountain (Mark 11:23)\n3. The effectual, fervent prayer of a righteous man avails much\n4. Pray the Word — it is the sword of the Spirit\n5. Authority is exercised from a place of submission to God",
  },
  {
    id: "ser9",
    title: "Fasting and Prayer",
    speaker: "Pastor [Name]",
    date: "2025-06-18",
    duration: "48:05",
    seriesId: "ss2",
    category: "Tuesday Bible Study",
    description: "The combination of fasting with prayer unlocks a dimension of spiritual power that prayer alone cannot reach. This teaching explores the different types of biblical fasts, the spiritual significance of fasting, and practical guidelines for effective fasting that produces breakthroughs.",
    scriptures: ["Isaiah 58:6-8", "Matthew 6:16-18", "Joel 2:12-13"],
    tags: ["fasting", "breakthrough", "spiritual power"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Fasting humbles the flesh and empowers the spirit\n2. God's chosen fast is to loose bonds of wickedness (Isa. 58:6)\n3. Jesus assumed His disciples would fast (Matt. 6:16)\n4. Fasting must be done with the right motive\n5. Combined with prayer, fasting breaks stubborn yokes",
  },
  {
    id: "ser10",
    title: "Persistent Prayer",
    speaker: "Evangelist Guest Speaker",
    date: "2025-07-04",
    duration: "1:12:05",
    seriesId: "ss2",
    category: "Special Programme",
    description: "Learning from the persistent widow in Luke 18, this powerful message by our guest evangelist demonstrates that importunate prayer — the kind that refuses to give up — always moves the hand of God. Your breakthrough may be just one more prayer away.",
    scriptures: ["Luke 18:1-8", "Matthew 7:7-11", "1 Thessalonians 5:17"],
    tags: ["persistence", "breakthrough", "faith"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Men ought always to pray and not lose heart (Luke 18:1)\n2. The widow's persistence moved an unjust judge — how much more our righteous God?\n3. Ask, seek, knock — keep pursuing until the door opens\n4. Pray without ceasing (1 Thess. 5:17)\n5. Your persistence is a demonstration of your faith in God's faithfulness",
  },
  {
    id: "ser11",
    title: "Intercessory Prayer",
    speaker: "Pastor [Name]",
    date: "2025-06-13",
    duration: "46:30",
    seriesId: "ss2",
    category: "Faith Clinic",
    description: "Standing in the gap for others is one of the highest forms of prayer. This message examines the ministry of intercession through the lives of Moses, Daniel, and Jesus Christ — our ultimate Intercessor — and challenges every believer to take up this vital ministry.",
    scriptures: ["Ezekiel 22:30", "1 Timothy 2:1-4", "Romans 8:34"],
    tags: ["intercession", "standing in the gap", "burden"],
    hasAudio: true,
    hasVideo: false,
    hasNotes: false,
  },

  // Series 3: The Grace Life
  {
    id: "ser12",
    title: "Understanding Grace",
    speaker: "Pastor [Name]",
    date: "2025-05-25",
    duration: "44:18",
    seriesId: "ss3",
    category: "Sunday Service",
    description: "A foundational teaching on what grace truly is, how it differs from mercy and the law, and why it is the bedrock of the Christian faith. Grace is not a licence to sin but the power to live righteously. This sermon will transform your understanding of God's unmerited favour.",
    scriptures: ["Ephesians 2:8-9", "Romans 6:14", "Titus 2:11-12"],
    tags: ["grace", "foundation", "salvation"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Grace is unmerited, undeserved favour\n2. By grace you have been saved through faith (Eph. 2:8)\n3. You are not under law but under grace (Rom. 6:14)\n4. Grace teaches us to say no to ungodliness (Titus 2:12)\n5. Where sin abounded, grace much more abounded",
  },
  {
    id: "ser13",
    title: "Grace for Every Season",
    speaker: "Pastor [Name]",
    date: "2025-05-18",
    duration: "46:30",
    seriesId: "ss3",
    category: "Sunday Service",
    description: "No matter what season of life you find yourself in — whether in the valley or on the mountaintop — God's grace is sufficient. This comforting yet challenging message reminds believers that grace is not just for salvation but for daily sustenance through every circumstance.",
    scriptures: ["2 Corinthians 12:9", "Hebrews 4:16", "Philippians 4:13"],
    tags: ["sufficiency", "seasons", "strength"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. My grace is sufficient for you (2 Cor. 12:9)\n2. Come boldly to the throne of grace (Heb. 4:16)\n3. I can do all things through Christ who strengthens me\n4. Grace is available in every season — you just need to receive it\n5. Strength is made perfect in weakness",
  },
  {
    id: "ser14",
    title: "Growing in Grace",
    speaker: "Pastor [Name]",
    date: "2025-05-11",
    duration: "43:12",
    seriesId: "ss3",
    category: "Tuesday Bible Study",
    description: "Just as physical growth requires intentional nourishment and exercise, spiritual growth in grace demands deliberate effort. This Bible Study message provides practical steps for growing in the grace and knowledge of our Lord Jesus Christ, moving from spiritual infancy to maturity.",
    scriptures: ["2 Peter 3:18", "1 Peter 2:2", "Hebrews 5:12-14"],
    tags: ["growth", "maturity", "spiritual development"],
    hasAudio: true,
    hasVideo: false,
    hasNotes: true,
    notes: "Key Points:\n\n1. Grow in grace and in the knowledge of Christ (2 Pet. 3:18)\n2. Desire the pure milk of the Word (1 Pet. 2:2)\n3. Move beyond the basics to solid food (Heb. 5:12-14)\n4. Growth requires consistency in prayer, Word, and fellowship\n5. Spiritual maturity is measured by love, not knowledge alone",
  },
  {
    id: "ser15",
    title: "Grace to Overcome",
    speaker: "Pastor [Name]",
    date: "2025-05-04",
    duration: "49:45",
    seriesId: "ss3",
    category: "Sunday Service",
    description: "Every believer faces temptations, trials, and challenges. But God's grace empowers us to overcome every single one. This message draws from the lives of Joseph, Daniel, and Paul to demonstrate that grace is not passive — it is active power working in and through us.",
    scriptures: ["1 Corinthians 10:13", "Romans 8:37", "James 4:7"],
    tags: ["overcoming", "temptation", "victory"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: false,
  },
  {
    id: "ser16",
    title: "The Throne of Grace",
    speaker: "Pastor [Name]",
    date: "2025-04-27",
    duration: "41:20",
    seriesId: "ss3",
    category: "Sunday Service",
    description: "The throne of grace is the most accessible yet most underutilised resource in the believer's life. This concluding message of The Grace Life series calls believers to come boldly, frequently, and confidently to obtain mercy and find help in time of need.",
    scriptures: ["Hebrews 4:14-16", "Romans 5:1-2", "Ephesians 3:12"],
    tags: ["throne of grace", "boldness", "access"],
    hasAudio: true,
    hasVideo: false,
    hasNotes: true,
    notes: "Key Points:\n\n1. We have a great High Priest who has passed through the heavens\n2. Come boldly to the throne of grace (Heb. 4:16)\n3. We have access by faith into this grace (Rom. 5:2)\n4. In Christ, we have boldness and access with confidence (Eph. 3:12)\n5. The throne of grace is always open — come often",
  },

  // Series 4: Spiritual Warfare
  {
    id: "ser17",
    title: "Know Your Enemy",
    speaker: "Pastor [Name]",
    date: "2025-04-24",
    duration: "58:20",
    seriesId: "ss4",
    category: "Faith Clinic",
    description: "You cannot fight an enemy you do not understand. This sermon exposes the strategies, tactics, and hierarchies of spiritual forces arrayed against believers, equipping you with the knowledge needed to stand firm and fight effectively.",
    scriptures: ["Ephesians 6:10-12", "1 Peter 5:8-9", "2 Corinthians 2:11"],
    tags: ["spiritual warfare", "enemy", "discernment"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. We wrestle not against flesh and blood (Eph. 6:12)\n2. The enemy roars like a lion seeking whom to devour\n3. We are not ignorant of his devices (2 Cor. 2:11)\n4. The enemy's primary weapons: deception, accusation, intimidation\n5. Knowledge of the enemy is the first step to victory",
  },
  {
    id: "ser18",
    title: "The Armour of God",
    speaker: "Pastor [Name]",
    date: "2025-04-17",
    duration: "1:02:15",
    seriesId: "ss4",
    category: "Tuesday Bible Study",
    description: "God has provided a complete set of spiritual armour for every believer. This comprehensive Bible Study message examines each piece of the armour — the belt of truth, breastplate of righteousness, shoes of the gospel, shield of faith, helmet of salvation, and sword of the Spirit.",
    scriptures: ["Ephesians 6:13-17", "Romans 13:12", "2 Corinthians 6:7"],
    tags: ["armour", "protection", "weapons"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Put on the whole armour of God (Eph. 6:13)\n2. Belt of truth — holds everything together\n3. Breastplate of righteousness — protects the heart\n4. Shield of faith — quenches every fiery dart\n5. Sword of the Spirit — the Word of God, your only offensive weapon",
  },
  {
    id: "ser19",
    title: "Victory in Christ",
    speaker: "Pastor [Name]",
    date: "2025-04-10",
    duration: "46:40",
    seriesId: "ss4",
    category: "Sunday Service",
    description: "The finished work of Christ on the cross guarantees our victory over every power of darkness. This message declares that the war has already been won — we are not fighting for victory but fighting from victory. Learn to enforce the triumph of Calvary in every area of your life.",
    scriptures: ["Colossians 2:15", "1 Corinthians 15:57", "Romans 8:31-39"],
    tags: ["victory", "triumph", "finished work"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Christ disarmed principalities and powers, making a public spectacle (Col. 2:15)\n2. Thanks be to God who gives us the victory (1 Cor. 15:57)\n3. If God is for us, who can be against us? (Rom. 8:31)\n4. Nothing can separate us from the love of God (Rom. 8:38-39)\n5. You fight from victory, not for victory",
  },
  {
    id: "ser20",
    title: "The Power of the Blood",
    speaker: "Pastor [Name]",
    date: "2025-04-03",
    duration: "52:10",
    seriesId: "ss4",
    category: "Faith Clinic",
    description: "The blood of Jesus is the most powerful weapon in the believer's arsenal. This opening message of the Spiritual Warfare series explores the redemptive, protective, and victorious power of the blood of the Lamb, and how to apply it in spiritual warfare.",
    scriptures: ["Revelation 12:11", "Hebrews 9:22", "1 Peter 1:18-19"],
    tags: ["blood of Jesus", "redemption", "protection"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: false,
  },

  // Series 5: Family Matters
  {
    id: "ser21",
    title: "Building a Godly Home",
    speaker: "Pastor [Name]",
    date: "2025-05-15",
    duration: "38:45",
    seriesId: "ss5",
    category: "Sunday Service",
    description: "The family is the first institution God created, long before the church or government. This message lays out foundational principles for building a home that honours God, rooted in love, mutual respect, prayer, and the Word of God.",
    scriptures: ["Joshua 24:15", "Psalm 127:1", "Deuteronomy 6:6-7"],
    tags: ["family", "home", "foundation"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. As for me and my house, we will serve the Lord (Josh. 24:15)\n2. Unless the Lord builds the house, they labour in vain (Ps. 127:1)\n3. Teach God's Word diligently to your children (Deut. 6:7)\n4. Prayer is the foundation of a godly home\n5. Love is the bond that holds everything together",
  },
  {
    id: "ser22",
    title: "Raising Godly Children",
    speaker: "Guest Speaker",
    date: "2025-05-08",
    duration: "1:05:30",
    seriesId: "ss5",
    category: "Special Programme",
    description: "In a world that is increasingly hostile to Christian values, raising children who love and serve God requires intentional, biblically grounded parenting. Our guest speaker delivers a powerful, practical message on nurturing children in the fear and admonition of the Lord.",
    scriptures: ["Proverbs 22:6", "Ephesians 6:4", "Deuteronomy 6:6-9"],
    tags: ["parenting", "children", "training"],
    hasAudio: true,
    hasVideo: true,
    hasNotes: true,
    notes: "Key Points:\n\n1. Train up a child in the way he should go (Prov. 22:6)\n2. Do not provoke your children to wrath (Eph. 6:4)\n3. Children are a heritage from the Lord\n4. Model what you teach — children learn by observation\n5. The home is the primary training ground, not the church",
  },
  {
    id: "ser23",
    title: "Marriage That Works",
    speaker: "Pastor [Name]",
    date: "2025-05-01",
    duration: "52:00",
    seriesId: "ss5",
    category: "Midweek Service",
    description: "Marriage was God's idea, and He provided the manual for its success. This midweek message delivers practical, biblical wisdom for building a strong, lasting, and fulfilling marriage — covering communication, submission, love, forgiveness, and the covenant nature of the marriage bond.",
    scriptures: ["Ephesians 5:22-33", "1 Corinthians 13:4-7", "Mark 10:6-9"],
    tags: ["marriage", "love", "covenant"],
    hasAudio: true,
    hasVideo: false,
    hasNotes: true,
    notes: "Key Points:\n\n1. Marriage is a covenant, not a contract\n2. Husbands, love your wives as Christ loved the church (Eph. 5:25)\n3. Wives, submit to your own husbands (Eph. 5:22)\n4. Love is patient, kind, does not envy or boast (1 Cor. 13:4)\n5. What God has joined together, let no man put asunder",
  },
  {
    id: "ser24",
    title: "Family Altar",
    speaker: "Pastor [Name]",
    date: "2025-04-24",
    duration: "35:15",
    seriesId: "ss5",
    category: "Tuesday Bible Study",
    description: "The family altar — a time of collective worship, prayer, and Bible study within the home — is one of the most powerful spiritual practices a family can establish. This Bible Study provides a practical guide for starting and maintaining a vibrant family altar that transforms your home.",
    scriptures: ["Joshua 24:15", "Psalm 133:1", "Matthew 18:20"],
    tags: ["family devotion", "altar", "worship"],
    hasAudio: true,
    hasVideo: false,
    hasNotes: false,
  },
];

export const allSpeakers = Array.from(
  new Set(mockSermons.map((s) => s.speaker))
).sort();