export const socialFeatures = [
  {
    id: "im-here",
    title: "I'm Here",
    emoji: "👋",
    description: "Let others know you're here right now",
    href: "/social/im-here",
    color: "from-[#1A237E] to-[#283593]",
    iconBg: "bg-blue-500",
  },
  {
    id: "todays-question",
    title: "Today's Question",
    emoji: "💬",
    description: "Answer today's community question",
    href: "/social/todays-question",
    color: "from-[#2E7D32] to-[#388E3C]",
    iconBg: "bg-green-500",
  },
  {
    id: "prayer-circle",
    title: "Prayer Circle",
    emoji: "🙏",
    description: "Share & pray for one another",
    href: "/social/prayer-circle",
    color: "from-[#D32F2F] to-[#E53935]",
    iconBg: "bg-red-500",
  },
  {
    id: "amen-wall",
    title: "Amen Wall",
    emoji: "❤️",
    description: "Post your faith declarations",
    href: "/social/amen-wall",
    color: "from-[#E65100] to-[#F57C00]",
    iconBg: "bg-orange-500",
  },
  {
    id: "weekly-challenge",
    title: "This Week's Challenge",
    emoji: "🔥",
    description: "Accept this week's community challenge",
    href: "/social/weekly-challenge",
    color: "from-[#6A1B9A] to-[#8E24AA]",
    iconBg: "bg-purple-500",
  },
  {
    id: "live-together",
    title: "Live Together",
    emoji: "🔴",
    description: "Worship together during live services",
    href: "/social/live-together",
    color: "from-[#C62828] to-[#D32F2F]",
    iconBg: "bg-red-600",
  },
  {
    id: "whos-coming",
    title: "Who's Coming?",
    emoji: "🙋",
    description: "See who's planning to attend",
    href: "/social/whos-coming",
    color: "from-[#00695C] to-[#00897B]",
    iconBg: "bg-teal-500",
  },
];
