export interface Ministry {
  id: string;
  name: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  meetingDay: string;
  meetingTime: string;
  icon: string;
  color: string;
  members: number;
  isOpen: boolean;
}

export const ministries: Ministry[] = [
  {
    id: "choir",
    name: "Choir / Music Ministry",
    description: "Lead the congregation in spirit-filled praise and worship during services and special programmes. If you have a passion for music, singing, or playing an instrument, this ministry is for you.",
    responsibilities: ["Lead worship during Sunday and midweek services", "Prepare songs and ministrations for special programmes", "Attend weekly rehearsal sessions", "Support other ministry events with music"],
    requirements: ["A genuine love for worship and music", "Ability to sing or play a musical instrument", "Commitment to weekly rehearsals and services", "Willingness to learn and grow musically and spiritually"],
    meetingDay: "Saturday",
    meetingTime: "4:00 PM - 6:00 PM",
    icon: "Music",
    color: "from-[#D32F2F] to-[#B71C1C]",
    members: 28,
    isOpen: true,
  },
  {
    id: "ushering",
    name: "Ushering Department",
    description: "Create a warm, orderly, and welcoming environment for all worshippers. Ushers are the first point of contact and set the tone for every service experience.",
    responsibilities: ["Welcome and seat worshippers as they arrive", "Maintain order and decorum during services", "Manage crowd flow and seating arrangements", "Assist with communion, offerings, and special service logistics"],
    requirements: ["A warm, friendly, and hospitable personality", "Neat appearance and professional demeanour", "Punctuality and reliability", "Physical ability to stand for extended periods"],
    meetingDay: "Saturday",
    meetingTime: "3:00 PM - 4:00 PM",
    icon: "DoorOpen",
    color: "from-[#1A237E] to-[#283593]",
    members: 18,
    isOpen: true,
  },
  {
    id: "children",
    name: "Children's Church",
    description: "Nurture and teach children in the ways of the Lord through age-appropriate Bible lessons, activities, worship, and fellowship. Shape the next generation for Christ.",
    responsibilities: ["Teach Bible lessons tailored to children's age groups", "Organise children's worship, games, and activities", "Prepare lesson materials and craft supplies", "Ensure child safety and welfare during sessions"],
    requirements: ["Love for children and patience", "Ability to teach and communicate with children", "Willingness to undergo child safety training", "Commitment to preparing lessons in advance"],
    meetingDay: "Saturday",
    meetingTime: "2:00 PM - 4:00 PM",
    icon: "Baby",
    color: "from-[#E65100] to-[#BF360C]",
    members: 14,
    isOpen: true,
  },
  {
    id: "youth",
    name: "Youth Ministry",
    description: "Engage, equip, and empower young people (ages 13-35) to live for God passionately. Through Bible study, mentorship, social activities, and outreach, we raise a generation of Kingdom champions.",
    responsibilities: ["Plan and execute youth-focused programmes and events", "Mentor and disciple young believers", "Organise outreach and evangelism activities", "Create a safe and engaging environment for spiritual growth"],
    requirements: ["Age 18-35 (or passion for youth work)", "Active relationship with God", "Ability to relate to and engage young people", "Creative and energetic approach to ministry"],
    meetingDay: "Saturday",
    meetingTime: "12:00 PM - 2:00 PM",
    icon: "Flame",
    color: "from-[#F57C00] to-[#E65100]",
    members: 32,
    isOpen: true,
  },
  {
    id: "media",
    name: "Media & Tech Ministry",
    description: "Handle all technical and media aspects of church services — live streaming, sound engineering, video production, social media, graphic design, and website management.",
    responsibilities: ["Operate sound systems during services", "Manage live stream setup and broadcasting", "Create graphics and social media content", "Handle photography and video recording of events"],
    requirements: ["Interest or experience in media/technology", "Willingness to learn technical skills", "Availability to arrive early for service setup", "Creative mindset and attention to detail"],
    meetingDay: "Saturday",
    meetingTime: "10:00 AM - 1:00 PM",
    icon: "MonitorSpeaker",
    color: "from-[#6A1B9A] to-[#4A148C]",
    members: 12,
    isOpen: true,
  },
  {
    id: "evangelism",
    name: "Evangelism & Outreach",
    description: "Take the Gospel beyond the church walls through street evangelism, community outreach, hospital visits, prison ministry, and missionary support. Fulfil the Great Commission.",
    responsibilities: ["Participate in organised outreach programmes", "Visit hospitals, prisons, and care homes", "Follow up on new converts and visitors", "Support missionary efforts locally and globally"],
    requirements: ["A burning passion for souls", "Boldness to share the Gospel", "Compassion for the lost and less privileged", "Willingness to dedicate time for outreach activities"],
    meetingDay: "Saturday",
    meetingTime: "9:00 AM - 11:00 AM",
    icon: "Globe",
    color: "from-[#2E7D32] to-[#1B5E20]",
    members: 22,
    isOpen: true,
  },
  {
    id: "welfare",
    name: "Welfare & Charity",
    description: "Demonstrate Christ's love through practical care for members and the community — welfare visits, financial assistance, food distribution, and support for the needy.",
    responsibilities: ["Visit sick and bereaved church members", "Coordinate food and material distribution", "Manage the welfare fund and disbursements", "Organise charity drives and community support programmes"],
    requirements: ["A heart of compassion and service", "Discretion and confidentiality", "Good organisational and record-keeping skills", "Availability for emergency welfare needs"],
    meetingDay: "1st Saturday of the month",
    meetingTime: "10:00 AM - 12:00 PM",
    icon: "Heart",
    color: "from-[#C62828] to-[#B71C1C]",
    members: 16,
    isOpen: true,
  },
  {
    id: "followup",
    name: "Follow-Up & Visitation",
    description: "Ensure no visitor or new convert falls through the cracks. This ministry tracks, visits, calls, and disciples new members until they are fully integrated into the church family.",
    responsibilities: ["Follow up on first-time visitors within 48 hours", "Conduct home and hospital visits", "Track member attendance and engagement", "Support new members in finding their place in the church"],
    requirements: ["Friendly, caring, and patient disposition", "Good communication and listening skills", "Availability to make visits and calls", "Knowledge of basic discipleship principles"],
    meetingDay: "2nd Saturday of the month",
    meetingTime: "11:00 AM - 1:00 PM",
    icon: "Phone",
    color: "from-[#1565C0] to-[#0D47A1]",
    members: 10,
    isOpen: true,
  },
  {
    id: "intercessors",
    name: "Intercessory Prayer Ministry",
    description: "A dedicated team that stands in the gap through consistent, fervent prayer for the church, the pastor, members, the community, the nation, and the nations of the world.",
    responsibilities: ["Commit to daily personal prayer times", "Attend weekly intercessory prayer meetings", "Pray for specific prayer requests submitted to the church", "Fast and pray during designated church prayer periods"],
    requirements: ["A deep prayer life and commitment to intercession", "Ability to keep prayer points and requests confidential", "Willingness to fast and pray consistently", "Sensitivity to the leading of the Holy Spirit"],
    meetingDay: "Every day (personal) + Saturday 7:00 AM - 9:00 AM",
    meetingTime: "7:00 AM - 9:00 AM (Saturdays)",
    icon: "Shield",
    color: "from-[#0D1557] to-[#1A237E]",
    members: 20,
    isOpen: true,
  },
  {
    id: "protocol",
    name: "Protocol & Hospitality",
    description: "Ensure smooth coordination of church services and events. Manage VIP handling, special guests, service logistics, and create a warm, dignified atmosphere for all church activities.",
    responsibilities: ["Coordinate service proceedings and timing", "Manage special guests and VIP reception", "Oversee logistics for church events", "Support the pastoral team with administrative coordination"],
    requirements: ["Excellent organisational skills", "Professional and dignified demeanour", "Attention to detail and ability to think ahead", "Strong communication and teamwork abilities"],
    meetingDay: "Saturday",
    meetingTime: "2:00 PM - 3:00 PM",
    icon: "Award",
    color: "from-[#37474F] to-[#263238]",
    members: 8,
    isOpen: true,
  },
];